/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { AdvertType } from './advertType';

export interface AdvertFormData {
  type?: AdvertType;
  email?: string;
  phone?: string;
  city?: string;
  district?: string;
  street?: string;
  houseCode?: string;
  flatNumber?: number;
  floor?: number;
  floors?: number;
  roomsNumber?: number;
  area?: number;
  livingArea?: number;
  price?: number;
  description?: string;
}
