/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export type AdvertType = typeof AdvertType[keyof typeof AdvertType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdvertType = {
  RENT: 'RENT',
  SALE: 'SALE',
} as const;
