/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export type AdvertStatus = typeof AdvertStatus[keyof typeof AdvertStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdvertStatus = {
  VISIBLE: 'VISIBLE',
  HIDDEN: 'HIDDEN',
  DELETED: 'DELETED',
} as const;
