export const advertS = [
    {
        "id": 28,
        "type": "RENT",
        "city": "Иваново",
        "district": "Port",
        "street": "пл. Первомайская, 714",
        "houseCode": "922",
        "flatNumber": 497,
        "floor": 49,
        "floors": 76,
        "roomsNumber": 6,
        "area": 243,
        "livingArea": 218.7,
        "price": 243000,
        "description": "Приятное жилище для вас! Всего за 243000 в месяц",
    },
    {
        "id": 29,
        "type": "RENT",

        "city": "Магнитогорск",
        "district": "North",
        "street": "пл. Трактовая, 078",
        "houseCode": "359",
        "flatNumber": 620,
        "floor": 62,
        "floors": 85,
        "roomsNumber": 6,
        "area": 242.5,
        "livingArea": 218.2,
        "price": 242000,
        "description": "Приятное жилище для вас! Всего за 242000 в месяц",
    },
    {
        "id": 30,
        "type": "RENT",

        "city": "Липецк",
        "district": "Lake",
        "street": "улица Западная, 374",
        "houseCode": "806",
        "flatNumber": 468,
        "floor": 46,
        "floors": 78,
        "roomsNumber": 3,
        "area": 72.8,
        "livingArea": 65.5,
        "price": 72000,
        "description": "Приятное жилище для вас! Всего за 72000 в месяц",
    },
    {
        "id": 31,
        "type": "RENT",

        "city": "Тверь",
        "district": "South",
        "street": "Полевая проспект, 748",
        "houseCode": "268",
        "flatNumber": 60,
        "floor": 6,
        "floors": 71,
        "roomsNumber": 6,
        "area": 276.7,
        "livingArea": 249,
        "price": 276000,
        "description": "Приятное жилище для вас! Всего за 276000 в месяц",
    },
    {
        "id": 32,
        "type": "RENT",

        "city": "Челябинск",
        "district": "Port",
        "street": "Речная пр., 499",
        "houseCode": "198",
        "flatNumber": 316,
        "floor": 31,
        "floors": 62,
        "roomsNumber": 5,
        "area": 124.7,
        "livingArea": 112.2,
        "price": 124000,
        "description": "Приятное жилище для вас! Всего за 124000 в месяц",
    },
    {
        "id": 33,
        "type": "RENT",

        "city": "Омск",
        "district": "Lake",
        "street": "ул. Строительная, 772",
        "houseCode": "313",
        "flatNumber": 35,
        "floor": 3,
        "floors": 27,
        "roomsNumber": 5,
        "area": 159.4,
        "livingArea": 143.4,
        "price": 159000,
        "description": "Приятное жилище для вас! Всего за 159000 в месяц",
    },
    {
        "id": 34,
        "type": "RENT",

        "city": "Екатеринбург",
        "district": "Port",
        "street": "Горького ул., 729",
        "houseCode": "655",
        "flatNumber": 91,
        "floor": 9,
        "floors": 15,
        "roomsNumber": 6,
        "area": 281,
        "livingArea": 252.9,
        "price": 281000,
        "description": "Приятное жилище для вас! Всего за 281000 в месяц",
    },
    {
        "id": 35,
        "type": "RENT",

        "city": "Барнаул",
        "district": "East",
        "street": "площадь Сосновая, 298",
        "houseCode": "213",
        "flatNumber": 242,
        "floor": 24,
        "floors": 25,
        "roomsNumber": 3,
        "area": 73.1,
        "livingArea": 65.7,
        "price": 73000,
        "description": "Приятное жилище для вас! Всего за 73000 в месяц",
    },
    {
        "id": 36,
        "type": "RENT",

        "city": "Пермь",
        "district": "New",
        "street": "Трудовая пл., 809",
        "houseCode": "369",
        "flatNumber": 222,
        "floor": 22,
        "floors": 27,
        "roomsNumber": 6,
        "area": 211.6,
        "livingArea": 190.4,
        "price": 211000,
        "description": "Приятное жилище для вас! Всего за 211000 в месяц",
    },
    {
        "id": 37,
        "type": "RENT",

        "city": "Санкт-Петербург",
        "district": "Lake",
        "street": "площадь Луговая, 442",
        "houseCode": "133",
        "flatNumber": 444,
        "floor": 44,
        "floors": 64,
        "roomsNumber": 6,
        "area": 215.6,
        "livingArea": 194,
        "price": 215000,
        "description": "Приятное жилище для вас! Всего за 215000 в месяц",
    }
];