/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export interface JwtResponse {
  type?: string;
  accessToken?: string;
  refreshToken?: string;
}
