/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { PageItemType } from './pageItemType';

export interface PageItem {
  pageItemType?: PageItemType;
  index?: number;
  active?: boolean;
}
