/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { PageUsers } from './pageUsers';
import type { Paging } from './paging';

export interface PagedUsers {
  page?: PageUsers;
  paging?: Paging;
}
