/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { PageAdverts } from './pageAdverts';
import type { Paging } from './paging';

export interface PagedAdverts {
  page?: PageAdverts;
  paging?: Paging;
}
