/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { PageableObject } from './pageableObject';
import type { Sort } from './sort';
import type { Adverts } from './adverts';

export interface PageAdverts {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  sort?: Sort;
  size?: number;
  content?: Adverts[];
  number?: number;
  numberOfElements?: number;
  empty?: boolean;
}
