/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { Sort } from './sort';

export interface PageableObject {
  pageNumber?: number;
  pageSize?: number;
  sort?: Sort;
  offset?: number;
  paged?: boolean;
  unpaged?: boolean;
}
