/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export type PageItemType = typeof PageItemType[keyof typeof PageItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageItemType = {
  DOTS: 'DOTS',
  PAGE: 'PAGE',
} as const;
