/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { PageItem } from './pageItem';

export interface Paging {
  nextEnabled?: boolean;
  prevEnabled?: boolean;
  pageSize?: number;
  pageNumber?: number;
  items?: PageItem[];
}
