/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export type RequestType = typeof RequestType[keyof typeof RequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestType = {
  RENT: 'RENT',
  SALE: 'SALE',
  VIEWING: 'VIEWING',
} as const;
