/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { RequestType } from './requestType';
import type { RequestStatus } from './requestStatus';

export interface Requests {
  id?: number;
  type?: RequestType;
  status?: RequestStatus;
  authorId?: number;
  advertId?: number;
}
