/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { RequestStatus } from './requestStatus';

export interface RequestStatusData {
  person?: number;
  status?: RequestStatus;
}
