/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */
import type { RequestType } from './requestType';

export interface RequestData {
  type?: RequestType;
  authorId?: number;
  advertId?: number;
}
