/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export type RequestStatus = typeof RequestStatus[keyof typeof RequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequestStatus = {
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  ACCEPTED: 'ACCEPTED',
  DELETED: 'DELETED',
} as const;
