/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * CityBoard API
 * OpenAPI spec version: v1
 */

export interface UserRegistrationData {
  username?: string;
  password?: string;
  name?: string;
  surname?: string;
  middle_name?: string;
}
